<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\..\Shared\StockManagement.Shared\StockManagement.Shared.csproj" />
    <ProjectReference Include="..\..\..\..\..\User\src\business\application\StockManagement.User.ApplicationContracts\StockManagement.Authentication.ApplicationContracts.csproj" />
  </ItemGroup>

</Project>
